service: s3-triggered-lambda

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1

functions:
  processJsonFiles:
    handler: handler.handler
    events:
      - s3:
          bucket: s3:/battery/
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json
plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - __pycache__/**

